server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  messages:
    basename: messages
  #  security:
  #    user:
  #      name: user
  #      password: 12345
  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

