server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  messages:
    basename: messages

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

